# Generated by Django 6.0.3 on 2026-03-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainunit',
            options={},
        ),
        migrations.AddField(
            model_name='carriage',
            name='image',
            field=models.ImageField(blank=True, default='carriage_images/default.png', upload_to='train_images/'),
        ),
    ]
