# Generated by Django 6.0.3 on 2026-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_trainunit_options_carriage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='image',
            field=models.ImageField(blank=True, default='carriage_images/default.png', upload_to='carriage_images/'),
        ),
    ]
